name: "Fake actions/setup-node"
description: Fake setup-node action
inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
runs:
  using: composite
  steps:
    - name: "Fake"
      shell: bash
      run: |
        echo "███████╗ █████╗ ██╗  ██╗███████╗"
        echo "██╔════╝██╔══██╗██║ ██╔╝██╔════╝"
        echo "█████╗  ███████║█████╔╝ █████╗  "
        echo "██╔══╝  ██╔══██║██╔═██╗ ██╔══╝  "
        echo "██║     ██║  ██║██║  ██╗███████╗"
        echo "╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝"